# Generated by Django 5.2.2 on 2025-06-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='captured_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='photo',
            field=models.FileField(upload_to='media'),
        ),
    ]
